<!DOCTYPE html>

<html lang="pt-br">

<head>
    <title lang="pt-br">HOME</title>
    <link rel="icon" href="blasek_logo.png">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

  <body>

    <div class="container mx-auto bg-light mt-1 w-90">
      <header class="row">
        <div id="barra_acessibilidade" class="col-12">
            
        </div>  
        <div class="col-sm-5">   
            <a href="home.html"><img src="blasek_logo.png" alt="HOME" width="150"></a>

        </div>
        <div class="col-sm-12">
          <h1>BLASEK</h1>
        </div>
        <nav>
          <ul>
            <li><a href="home.html">HOME</a></li>
            <li><a href="2.html">O significado da tecnologia em nossa vida cotidiana</a></li>
            <li><a href="3.html">Tecnologia hoje: por que é importante e como ajuda</a></li>
            <li><a href="formulario.html">FORMULARIO DE CONTATO</a></li>
          </ul>   
        </nav>
            <h2>ESTE BLOG É PARA RESUMIR UM POUCO NOSSA VIDA HOJE EM DIA COM AS NOVAS TECNOLOGIAS QUE SURGEM A CADA DIA MAIS.</h2>
      </header>
        

      <footer class="row">
        <div class="col-12">
          <p>Copyright © 2023</p>
        </div>
      </footer>
    </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <noscript>Atualize seu navegador</noscript>

  </body>

</html>